#!/bin/bash

APP_NAME="caches-manager"

set -euo pipefail
shopt -s nullglob

create_cache() {
    mkdir -p "$1"
    [ -e "$2" ] && rm -r "$2"
    ln -sT "$1" "$2" || true
}

declare -a TARGETS

read_config() {
    while read -r line || [ -n "${line}" ]; do
        [ "${line}" ] && TARGETS+=("${line}")
    done < "$1"
}

read_configs_from() {
    [ -d "$1" ] || return

    for f in "$1/"*.conf; do
        read_config "${f}"
    done
}

create_system_caches() {
    local dir="/dev/shm"
    [ -d "${dir}" ] || return 2

    TARGETS=()
    read_configs_from "/etc/${APP_NAME}/system"

    for t in "${TARGETS[@]}"; do
        create_cache "${dir}/tmp/${t}" "${t}"
    done
}

create_user_caches() {
    local dir="${XDG_RUNTIME_DIR:-"/run/user/${UID}"}"
    [ -d "${dir}" ] || return 2

    TARGETS=()
    read_configs_from "/etc/${APP_NAME}/user"
    read_configs_from "${XDG_CONFIG_HOME:-"${HOME}/.config"}/${APP_NAME}"

    for t in "${TARGETS[@]}"; do
        create_cache "${dir}/tmp/${t}" "${HOME}/${t}"
    done
}

declare -A ARGS=()

for arg in "$@"; do
    ARGS["${arg}"]=1
done

if [ -v "ARGS['--system']" ]; then
    if ((UID == 0)); then
        create_system_caches
    else
        echo "System job requires root privileges."
        exit 13
    fi
fi

if [ -v "ARGS['--user']" ]; then
    create_user_caches
fi
